# https://hub.docker.com/r/franzinc/agraph/tags?page=1&ordering=last_updated

FROM franzinc/agraph:v7.2.0

# nope, can only do this after agraph generates it: 
#RUN sudo -c echo -e "CorsAllowOrigin www.irisa.fr\nCorsAllowCredentials yes\n" >> /agraph/etc/agraph.cfg


