# Generated by Django 3.2.11 on 2022-01-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
