FROM koo5/ubuntu

WORKDIR /app/
ARG REQUIREMENTS_FILE=requirements-dev.txt

COPY worker/${REQUIREMENTS_FILE} /app/sources/worker/
RUN python3 -m pip install --upgrade --no-cache-dir -r /app/sources/worker/${REQUIREMENTS_FILE}

COPY common/ /app/sources/common/


RUN mkdir -p /app/server_root/tmp
RUN chown myuser:myuser /app/server_root/tmp
USER myuser
VOLUME /app/server_root/tmp
VOLUME /app/sources/


ENV PYTHONUNBUFFERED=1
ENV WATCHMEDO_INTERVAL=5
ENV WATCHMEDO=true


WORKDIR /app/sources/worker

CMD ["./start.sh"]
HEALTHCHECK CMD curl http://127.0.0.1:1111 --fail
