FROM koo5/ubuntu

WORKDIR /app/
ARG REQUIREMENTS_FILE=requirements.txt

COPY download_bastion/${REQUIREMENTS_FILE} /app/sources/bastion/
RUN python3 -m pip install --upgrade --no-cache-dir -r /app/sources/bastion/${REQUIREMENTS_FILE}


EXPOSE 6457
RUN mkdir -p /app/server_root/tmp
RUN chown myuser:myuser /app/server_root/tmp
USER myuser
VOLUME /app/server_root/tmp
VOLUME /app/sources/

ENV PYTHONUNBUFFERED=1
ENV WATCHMEDO_INTERVAL=5
ENV WATCHMEDO=true


WORKDIR /app/sources/download

CMD ["./start.sh"]
HEALTHCHECK CMD curl http://127.0.0.1:6457
