FROM koo5/ubuntu

WORKDIR /app/sources/common
COPY common/libs /app/sources/common/libs
COPY frontend_server/requirements_minimal.txt .
RUN python3.9 -m pip install --no-cache-dir -r requirements_minimal.txt

WORKDIR /app


EXPOSE 7788
RUN mkdir -p /app/server_root
VOLUME /app/server_root
VOLUME /app/sources/
USER myuser
WORKDIR /app/sources/frontend_server
ENTRYPOINT ["./start.sh"]
CMD ["0.0.0.0:7788"]
