FROM ubuntu:20.04
RUN apt-get update && apt-get install -y git python3.9 python3-pip \
 && rm -rf /var/lib/apt/lists/*
RUN mkdir /app
WORKDIR /app
COPY frontend_server/requirements_minimal.txt .
RUN pip3 install --no-cache-dir -r requirements_minimal.txt
EXPOSE 7788
RUN mkdir -p /app/server_root


VOLUME /app/server_root
VOLUME /app/sources/


ARG uid=1000
ARG gid=1000
RUN groupadd -g $gid myuser && useradd -lm -u $uid -g $gid myuser
USER myuser


WORKDIR /app/sources/frontend_server
ENV PYTHONUNBUFFERED true
ENV PYTHONDONTWRITEBYTECODE 1
ENV CELERY_QUEUE_NAME=q7788
ENTRYPOINT ["./start.sh"]
CMD ["0.0.0.0:7788"]
