FROM ubuntu:18.04

RUN apt-get update && apt-get install  -y apache2 \
    libapache2-mod-wsgi \
    build-essential \
    python3 \
#    python3-dev\
    python3-pip \
    vim \
 && apt-get clean \
 && apt-get autoremove \
 && rm -rf /var/lib/apt/lists/*

RUN a2enmod headers
EXPOSE 80




COPY apache/000-default.conf /etc/apache2/sites-available/



RUN mkdir /app
WORKDIR /app
COPY frontend_server/requirements.txt frontend_server/requirements.txt
RUN pip3 install --no-cache-dir -r frontend_server/requirements.txt
RUN mkdir -p /app/server_root
#RUN chown -R user:user /app/server_root
#RUN chown -R user:user /app/server_root
VOLUME /app/server_root
COPY frontend_server ./frontend_server
COPY internal_workers ./internal_workers
COPY static ./static
COPY git_info.txt .
COPY secrets1.json /
COPY secrets2.json /
WORKDIR /app/frontend_server
ENV PYTHONUNBUFFERED true
ENV CELERY_QUEUE_NAME=q7788
#ENTRYPOINT ["./start.sh"]
#CMD ["--noreload", "0.0.0.0:7788"]
CMD  /usr/sbin/apache2ctl -D FOREGROUND
