FROM alpine

RUN apk add --no-cache  apache2 \
    apache2-mod-wsgi \
    py3-pip \
    python3 

#RUN a2enmod headers

RUN mkdir /app
WORKDIR /app
COPY frontend_server/requirements.txt frontend_server/requirements.txt
RUN pip install --no-cache-dir -r frontend_server/requirements.txt

RUN mkdir -p /app/server_root
#RUN chown -R user:user /app/server_root
#RUN chown -R user:user /app/server_root
VOLUME /app/server_root
COPY frontend_server ./frontend_server
COPY internal_workers ./internal_workers
COPY static ./static
COPY git_info.txt .
COPY secrets1.json /
COPY secrets2.json /
WORKDIR /app/frontend_server
ENV PYTHONUNBUFFERED true
ENV CELERY_QUEUE_NAME=q7788
COPY apache/000-default.conf /etc/apache2/conf.d/
EXPOSE 80
CMD ["-D", "FOREGROUND"]
ENTRYPOINT ["/usr/sbin/httpd"]
