FROM koo5/ubuntu

EXPOSE 7788
RUN mkdir -p /app/server_root
VOLUME /app/server_root
VOLUME /app/sources/

RUN apt install wget

USER myuser

ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV PYTHONUNBUFFERED=1
ENV WATCHMEDO_INTERVAL=5
ENV WATCHMEDO=true


WORKDIR /app/sources/services
COPY services/requirements.txt .
RUN python3 -m pip install --user --upgrade --no-cache-dir -r requirements.txt
HEALTHCHECK CMD curl http://127.0.0.1:17788/
CMD ["./start.sh"]
