FROM koo5/ubuntu

RUN apt-get install -y libpq-dev
WORKDIR /app/sources
COPY wait-for-it wait-for-it

COPY remoulade_api/requirements.txt remoulade_api/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /app/sources/remoulade_api/requirements.txt


COPY common/libs/remoulade common/libs/remoulade

RUN python3 -m pip install --no-cache-dir -e /app/sources/common/libs/remoulade[rabbitmq,redis,postgres]

COPY remoulade_api remoulade_api
COPY internal_workers internal_workers

ENV FLASK_APP=main
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV PYTHONUNBUFFERED=1

# i think we should do it the other way around. Everything's copied at build, but later /app/sources can be made a volume
VOLUME /app/sources/ 

WORKDIR /app/sources/remoulade_api

ENTRYPOINT ["/app/sources/remoulade_api/start.sh"]

