FROM koo5/ubuntu

RUN apt-get install -y libpq-dev

WORKDIR /app

COPY manager/requirements.txt .
COPY manager/requirements-dev.txt .

RUN python3 -m pip install  --upgrade --no-cache-dir -r requirements.txt
RUN python3 -m pip install  --upgrade --no-cache-dir -r requirements-dev.txt




COPY common/libs /app/sources/common/libs
RUN chown myuser:myuser /app/
RUN chown myuser:myuser /home/myuser

USER root
# this has to be made writeable because python wants to write it's eggs in there
RUN chown -R myuser:myuser /app/sources/common/libs/remoulade/
USER myuser

USER root
# you can't run this as non-root, because python insists on writing some random stuff somewhere random around the filesystem. Also, you can't install in develop mode (-e), because python insists on writing random stuff into the sources directory and then expects to find it there (which it wont if the sources directory gets mounted over by a volume for runtime). 2023, people, 2023.
RUN PYTHONUSERBASE=/home/myuser/.local python3 -m pip install --upgrade --ignore-installed --user  /app/sources/common/libs/remoulade/[rabbitmq,redis,postgres]

USER myuser


WORKDIR /app/sources/manager/
RUN mkdir -p /app/server_root/tmp
RUN mkdir -p /app/server_root/control
RUN chown myuser:myuser /app/server_root/tmp
RUN chown myuser:myuser /app/server_root/control
VOLUME /app/server_root/tmp
RUN chown myuser:myuser /app/server_root/tmp


RUN mkdir -p /app/cache
RUN chown myuser:myuser /app/cache
VOLUME /app/cache


VOLUME /app/sources/
VOLUME /app/tests/

RUN chown myuser:myuser /app/server_root/


ENV WATCHMEDO_INTERVAL=5
ENV WATCHMEDO=true

CMD ["/app/sources/manager/start.sh"]
HEALTHCHECK CMD /bin/true
