FROM koo5/ubuntu
ARG APPDIR
ARG APPPATH









# python requirements (common block)
USER myuser:myuser
WORKDIR $APPPATH
COPY $APPDIR/requirements.txt .
COPY $APPDIR/requirements-dev.txt .
RUN PYTHONUSERBASE=/home/myuser/.local python3 -m pip install --upgrade --ignore-installed --user --no-cache-dir -r requirements.txt
RUN PYTHONUSERBASE=/home/myuser/.local python3 -m pip install --upgrade --ignore-installed --user --no-cache-dir -r requirements-dev.txt
USER root






# remoulade (common block)

RUN apt-get install -y libpq-dev
# this has to be made writeable because python wants to write it's eggs in there
COPY --chown=myuser:myuser common/libs/remoulade/ /app/sources/common/libs/remoulade/
USER myuser:myuser
RUN PYTHONUSERBASE=/home/myuser/.local python3 -m pip install -v --upgrade --ignore-installed --user /app/sources/common/libs/remoulade/[rabbitmq,redis,postgres]







WORKDIR $APPPATH
USER myuser
CMD ["./start.sh"]
ENV HC="curl -L -S --fail http://127.0.0.1:9111/health" 






#start interval is the time between health checks during the start period. This option requires Docker Engine version 25.0 or later.
HEALTHCHECK --interval=2s --timeout=60s CMD { test -f /healthcheck/ok && echo -n "sleep.." && sleep 55 && echo -n "hc..>> " && /bin/sh -c '/bin/sh -c "$HC"' && echo -n " <<..hc passed." ; } || { echo -n "hc..>> " && echo -n "$HC" && echo -n " <<... " && /bin/sh -c '/bin/sh -c "$HC"' && echo -n " << first hc passed." && touch /healthcheck/ok && echo " flag stored." ; } 
