FROM koo5/ubuntu




RUN apt-get install -qqy git python3.9 python3.9-dev python3-pip libcurl4-gnutls-dev libssl-dev libgnutls28-dev
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir /app
WORKDIR /app


COPY common/rq /app/sources/common/rq
COPY requirements.txt .
RUN python3.9 -m pip install --no-cache-dir -r requirements.txt 


EXPOSE 17788
RUN mkdir -p /app/server_root
VOLUME /app/server_root
VOLUME /app/sources/


ARG uid=1000
ARG gid=1000
RUN groupadd -g $gid myuser && useradd -lm -u $uid -g $gid myuser
USER myuser


WORKDIR /app/sources/internal_services
ENV PYTHONUNBUFFERED true
ENTRYPOINT ["./start.sh"]
CMD ["0.0.0.0:17788"]
