FROM koo5/ubuntu

RUN apt-get install -qqy libpq-dev

WORKDIR /app/

COPY frontend_server/requirements_minimal.txt /app/sources/frontend_server_fastapi_wip/requirements.txt
RUN python3.9 -m pip install --upgrade --no-cache-dir -r /app/sources/frontend_server_fastapi_wip/requirements.txt

COPY common/ /app/sources/common/
RUN python3.9 -m pip install --no-cache-dir -e /app/sources/common/libs/remoulade[rabbitmq,redis,postgres]


ENV PYTHONPATH=/app/sources/common/libs/remoulade/



EXPOSE 7788
RUN mkdir -p /app/server_root
VOLUME /app/server_root
VOLUME /app/sources/
USER myuser



WORKDIR /app/sources/frontend_server_fastapi_wip/

CMD ["start.sh"]
