FROM koo5/ubuntu
ARG APPDIR
ARG APPPATH




# python requirements (common block)

WORKDIR $APPPATH
COPY $APPDIR/requirements.txt .
COPY $APPDIR/requirements-dev.txt .
RUN PYTHONUSERBASE=/home/myuser/.local python3 -m pip install --upgrade --ignore-installed --user --no-cache-dir -r requirements.txt
RUN PYTHONUSERBASE=/home/myuser/.local python3 -m pip install --upgrade --ignore-installed --user --no-cache-dir -r requirements-dev.txt
RUN chown -vR myuser:myuser /home/myuser





WORKDIR $APPPATH
USER myuser
HEALTHCHECK CMD curl http://127.0.0.1:17788/
CMD ["./start.sh"]
