FROM koo5/ubuntu

WORKDIR /app/sources/common
COPY common/libs /app/sources/common/libs
COPY requirements.txt .
RUN python3.9 -m pip install --no-cache-dir -r requirements.txt

WORKDIR /app



RUN     apt-get install -qqy \
        git \
        build-essential cmake ninja-build pkg-config \
        ncurses-dev libreadline-dev libedit-dev \
        libunwind-dev \
        libgmp-dev \
        libssl-dev \
        unixodbc-dev \
        zlib1g-dev libarchive-dev \
        libossp-uuid-dev \
        libxext-dev libice-dev libjpeg-dev libxinerama-dev libxft-dev \
        libxpm-dev libxt-dev \
        libdb-dev \
        libpcre3-dev \
        libyaml-dev \
        libcurl4-gnutls-dev \
        libgnutls28-dev \
        libtcmalloc-minimal4 \
        python3.9 python3.9-dev python3-pip




RUN rm -rf /var/lib/apt/lists/*




RUN uname -a
RUN gcc -v 2>&1
#RUN git clone --branch V8.3.10 https://github.com/SWI-Prolog/swipl.git swipl
#RUN git clone --branch V8.1.15 https://github.com/SWI-Prolog/swipl.git swipl
#RUN git clone --recurse-submodules  --depth 1 -b V8.3.18  "https://github.com/SWI-Prolog/swipl-devel.git" 	 swipl
#RUN git clone --recurse-submodules  -b V8.3.18  "https://github.com/SWI-Prolog/swipl-devel.git" 	 swipl
#RUN git clone --recurse-submodules  --depth 1 -b V8.3.28  "https://github.com/koo5/swipl-devel.git"       swipl
RUN git clone --recurse-submodules  --depth 1 -b V8.3.18  "https://github.com/SWI-Prolog/swipl-devel.git"       swipl

#RUN git clone --depth 1 -b master  "https://github.com/SWI-Prolog/swipl-devel.git"       swipl
WORKDIR swipl
#RUN git reset a624386fa4c4718866a906e597e92b8b1b048382 --hard
#RUN git submodule update --init --recursive

#RUN git remote add koo5 "https://github.com/koo5/swipl-devel.git"
#RUN git fetch koo5
#RUN git cherry-pick -n koo5/dev1
##RUN git cherry-pick -n origin/dev1

#RUN git clone "https://github.com/SWI-Prolog/swipl-devel.git" 	 swipl
#RUN git reset 32f8079a1c6d9651d0825dcadce9f80231b01648 --hard
#RUN git submodule update --init --recursive

#RUN git checkout V8.3.20
#RUN git checkout 9defc51a1e328f095c6e51bb41693d2115ab0cff
#RUN git checkout 6d26b69c9f1ce6304683e86afc5bcf1621150524
#RUN git submodule update --init --recursive

WORKDIR packages/xpce
RUN true
RUN git remote add koo5 https://github.com/koo5/packages-xpce.git #
RUN date
RUN git fetch koo5
RUN git cherry-pick -n koo5/more_eye_friendly_gtrace_color_theme5
#RUN git cherry-pick -n koo5/dev1


WORKDIR /app/swipl
RUN mkdir build
WORKDIR build
RUN cmake -G Ninja ..
RUN ninja
RUN ctest -j 8 --output-on-failure; true
RUN ninja install


WORKDIR /app


RUN mkdir -p /app/server_root/tmp
RUN mkdir -p /app/server_root/control
RUN chown myuser:myuser /app/server_root/tmp
RUN chown myuser:myuser /app/server_root/control


VOLUME /app/server_root
VOLUME /app/cache
VOLUME /app/sources/
VOLUME /app/tests/
WORKDIR /app/sources/internal_workers
VOLUME /root/.config/swi-prolog/xpce/




RUN chown myuser:myuser /app/server_root/
USER myuser
ENV CELERY_QUEUE_NAME=q7788
ENV DETERMINANCY_CHECKER__USE__ENFORCER=true
COPY init_prolog.sh .
RUN ./init_prolog.sh
ENTRYPOINT ["./start.sh"]
CMD ["-n", "worker7788", "--loglevel=INFO"]

