:- use_module(library(xpath)).

dom([ element(reports,
	  [ 'xmlns:xsi' = 'http://www.w3.org/2001/XMLSchema-instance',
	    'xmlns:xsd' = 'http://www.w3.org/2001/XMLSchema'
	  ],
	  [ '\n  ',
	    element(balanceSheetRequest,
		    [],
		    [ '\n    ',
		      element(generator,
			      [],
			      [ '\n      ',
				element(date,
					[],
					['2014-08-28T10:58:40.000165Z']),
				'\n      ',
				element(source,[],['LODGEIT']),
				'\n      ',
				element(author,
					[],
					[ '\n        ',
					  element(firstname,[],['David']),
					  '\n        ',
					  element(lastname,[],['Joe']),
					  '\n        ',
					  element(company,
						  [],
						  ['XYZ Company Pvt Ltd']),
					  '\n      '
					]),
				'\n    '
			      ]),
		      '\n    ',
		      element(company,
			      [],
			      [ '\n      ',
				element(abn,[],['11111111111']),
				'\n      ',
				element(anzsic,[],[]),
				'\n    '
			      ]),
		      '\n    \n    ',
		      element(startDate,[],['2015-07-01']),
		      '\n    \n    ',
		      element(endDate,[],['2018-06-30']),
		      '\n    \n    ',
		      element(defaultUnitTypes,
			      [],
			      [ '\n      ',
				element(unitType,[],['AUD']),
				'\n    '
			      ]),
		      '\n    \n    ',
		      element(unitValues,
			      [],
			      [ '\n      ',
				element(unitValue,
					[],
					[ '\n        ',
					  element(unitType,[],['BHP']),
					  '\n        ',
					  element(unitValue,[],['2']),
					  '\n        ',
					  element(unitValueCurrency,
						  [],
						  ['USD']),
					  '\n      '
					]),
				'\n      ',
				element(unitValue,
					[],
					[ '\n        ',
					  element(unitType,[],['TLS']),
					  '\n        ',
					  element(unitValue,[],['5']),
					  '\n        ',
					  element(unitValueCurrency,
						  [],
						  ['AUD']),
					  '\n      '
					]),
				'\n    '
			      ]),
		      '\n    ',
		      element(bankStatement,
			      [],
			      [ '\n      ',
				element(title,[],['Bank Statement']),
				'\n      ',
				element(period,
					[],
					['2010-01-01 - 2010-06-30']),
				'\n      ',
				element(accountDetails,
					[],
					[ '\n        ',
					  element(accountNo,
						  [],
						  ['1-1110']),
					  '\n        \n        ',
					  element(accountName,
						  [],
						  [ 'NationalAustraliaBank'
						  ]),
					  '\n        ',
					  element(dateofBankStatement,
						  [],
						  ['2018-09-30']),
					  '\n        ',
					  element(bankID,
						  [],
						  ['Commonwealth Bank']),
					  '\n        ',
					  element(currency,[],['AUD']),
					  '\n        ',
					  element(transactions,
						  [],
						  [ '\n          ',
						    element(transaction,
							    [],
							    [ '\n            ',
							      element(transdesc,
								      [],
								      [ 'Borrow'
								      ]),
							      '\n            ',
							      element(transdate,
								      [],
								      [ '2017-08-01'
								      ]),
							      '\n            ',
							      element(debit,
								      [],
								      [ '0'
								      ]),
							      '\n            ',
							      element(credit,
								      [],
								      [ '100'
								      ]),
							      '\n          '
							    ]),
						    '\n          ',
						    element(transaction,
							    [],
							    [ '\n            \n            ',
							      element(transdesc,
								      [],
								      [ 'Invest_In'
								      ]),
							      '\n            ',
							      element(transdate,
								      [],
								      [ '2018-08-02'
								      ]),
							      '\n            ',
							      element(debit,
								      [],
								      [ '50'
								      ]),
							      '\n            ',
							      element(credit,
								      [],
								      [ '0'
								      ]),
							      '\n            \n            ',
							      element(unit,
								      [],
								      [ '10'
								      ]),
							      '\n            ',
							      element(unitType,
								      [],
								      [ 'TLS'
								      ]),
							      '\n          '
							    ]),
						    '\n        '
						  ]),
					  '\n      '
					]),
				'\n      ',
				element(accountDetails,
					[],
					[ '\n        ',
					  element(accountNo,
						  [],
						  ['1-1110']),
					  '\n        ',
					  element(accountName,
						  [],
						  ['WellsFargo']),
					  '\n        ',
					  element(dateofBankStatement,
						  [],
						  ['2018-09-30']),
					  '\n        ',
					  element(bankID,
						  [],
						  ['Commonwealth Bank']),
					  '\n        ',
					  element(currency,[],['USD']),
					  '\n        ',
					  element(transactions,
						  [],
						  [ '\n          ',
						    element(transaction,
							    [],
							    [ '\n            ',
							      element(transdesc,
								      [],
								      [ 'Introduce_Capital'
								      ]),
							      '\n            ',
							      element(transdate,
								      [],
								      [ '2017-07-01'
								      ]),
							      '\n            ',
							      element(debit,
								      [],
								      [ '0'
								      ]),
							      '\n            ',
							      element(credit,
								      [],
								      [ '200'
								      ]),
							      '\n          '
							    ]),
						    '\n          ',
						    element(transaction,
							    [],
							    [ '\n            ',
							      element(transdesc,
								      [],
								      [ 'Invest_In'
								      ]),
							      '\n            ',
							      element(transdate,
								      [],
								      [ '2017-07-10'
								      ]),
							      '\n            ',
							      element(debit,
								      [],
								      [ '100.00'
								      ]),
							      '\n            ',
							      element(credit,
								      [],
								      [ '0.00'
								      ]),
							      '\n            ',
							      element(unit,
								      [],
								      [ '10'
								      ]),
							      '\n            ',
							      element(unitType,
								      [],
								      [ 'BHP'
								      ]),
							      '\n          '
							    ]),
						    '\n          ',
						    element(transaction,
							    [],
							    [ '\n            ',
							      element(transdesc,
								      [],
								      [ 'PayBank'
								      ]),
							      '\n            ',
							      element(transdate,
								      [],
								      [ '2018-06-28'
								      ]),
							      '\n            ',
							      element(debit,
								      [],
								      [ '10'
								      ]),
							      '\n            ',
							      element(credit,
								      [],
								      [ '0.00'
								      ]),
							      '\n          '
							    ]),
						    '\n        '
						  ]),
					  '\n      '
					]),
				'\n    '
			      ]),
		      '\n\n',
		      element(actionTaxonomy,
			      [],
			      [ '\n  ',
				element(action,
					[],
					[ '\n    ',
					  element(id,[],['Invest_In']),
					  '\n    ',
					  element(description,
						  [],
						  ['Shares']),
					  '\n    ',
					  element(exchangeAccount,
						  [],
						  [ 'FinancialInvestments'
						  ]),
					  '\n    ',
					  element(tradingAccount,
						  [],
						  ['InvestmentIncome']),
					  '\n  '
					]),
				'\n  ',
				element(action,
					[],
					[ '\n    ',
					  element(id,[],['Dispose_Off']),
					  '\n    ',
					  element(description,
						  [],
						  ['Shares']),
					  '\n    ',
					  element(exchangeAccount,
						  [],
						  [ 'FinancialInvestments'
						  ]),
					  '\n    ',
					  element(tradingAccount,
						  [],
						  ['InvestmentIncome']),
					  '\n  '
					]),
				'\n  ',
				element(action,
					[],
					[ '\n    ',
					  element(id,[],['Borrow']),
					  '\n    ',
					  element(description,
						  [],
						  ['Shares']),
					  '\n    ',
					  element(exchangeAccount,
						  [],
						  ['NoncurrentLoans']),
					  '\n    ',
					  element(tradingAccount,
						  [],
						  ['InvestmentIncome']),
					  '\n  '
					]),
				'\n  ',
				element(action,
					[],
					[ '\n    ',
					  element(id,
						  [],
						  ['Introduce_Capital']),
					  '\n    ',
					  element(description,
						  [],
						  ['Unit_Investment']),
					  '\n    ',
					  element(exchangeAccount,
						  [],
						  ['ShareCapital']),
					  '\n    ',
					  element(tradingAccount,
						  [],
						  ['InvestmentIncome']),
					  '\n  '
					]),
				'\n  ',
				element(action,
					[],
					[ '\n    ',
					  element(id,[],['Gain']),
					  '\n    ',
					  element(description,
						  [],
						  ['Unit_Investment']),
					  '\n    ',
					  element(exchangeAccount,
						  [],
						  ['ShareCapital']),
					  '\n    ',
					  element(tradingAccount,
						  [],
						  ['InvestmentIncome']),
					  '\n  '
					]),
				'\n  ',
				element(action,
					[],
					[ '\n    ',
					  element(id,[],['Loss']),
					  '\n    ',
					  element(description,
						  [],
						  ['No Description']),
					  '\n    ',
					  element(exchangeAccount,
						  [],
						  ['ShareCapital']),
					  '\n    ',
					  element(tradingAccount,
						  [],
						  ['InvestmentIncome']),
					  '\n  '
					]),
				'\n  ',
				element(action,
					[],
					[ '\n    ',
					  element(id,[],['PayBank']),
					  '\n    ',
					  element(description,
						  [],
						  ['No Description']),
					  '\n    ',
					  element(exchangeAccount,
						  [],
						  ['BankCharges']),
					  '\n    ',
					  element(tradingAccount,
						  [],
						  ['InvestmentIncome']),
					  '\n  '
					]),
				'\n'
			      ]),
		      '\n\n  '
		    ]),
	    '\n'
	  ])
]).



