FROM koo5/ubuntu

RUN apt-get install -y libpq-dev

WORKDIR /app/

USER myuser

COPY frontend/requirements.txt .
COPY frontend/requirements-dev.txt .

RUN python3 -m pip install  --upgrade --no-cache-dir -r requirements.txt
RUN python3 -m pip install  --upgrade --no-cache-dir -r requirements-dev.txt
# dont think we still need to install this separately?
COPY common/ /app/sources/common/

USER root
# you can't run this as non-root, because python insists on writing some random stuff somewhere random around the filesystem. Also, you can't install in develop mode (-e), because python insists on writing random stuff into the sources directory and then expects to find it there (which it wont if the sources directory gets mounted over by a volume for runtime). 2023, people, 2023.
RUN PYTHONUSERBASE=/home/myuser/.local python3 -m pip install --upgrade --ignore-installed --user  /app/sources/common/libs/remoulade/[rabbitmq,redis,postgres]

EXPOSE 7788
RUN mkdir -p /app/server_root/tmp
RUN chown myuser:myuser /app/server_root/tmp
USER myuser
VOLUME /app/server_root/tmp
VOLUME /app/sources/


ENV PYTHONUNBUFFERED=1
ENV WATCHMEDO_INTERVAL=5
ENV WATCHMEDO=true


WORKDIR /app/sources/frontend

CMD ["./start.sh"]
HEALTHCHECK CMD curl http://127.0.0.1:7788
