FROM koo5/ubuntu

RUN apt-get install -y libpq-dev

WORKDIR /app/

COPY frontend_server_fastapi_wip/requirements.txt /app/sources/frontend_server_fastapi_wip/requirements.txt
RUN python3 -m pip install --upgrade --no-cache-dir -r /app/sources/frontend_server_fastapi_wip/requirements.txt

COPY common/ /app/sources/common/
RUN python3 -m pip install --no-cache-dir -e /app/sources/common/libs/remoulade[rabbitmq,redis,postgres]


#ENV PYTHONPATH=/app/sources/common/libs/remoulade/



EXPOSE 7788
RUN mkdir -p /app/server_root
VOLUME /app/server_root
VOLUME /app/sources/
USER myuser



WORKDIR /app/sources/frontend_server_fastapi_wip/

CMD ["./start.sh"]
HEALTHCHECK CMD curl http://127.0.0.1:7788