on: [ push ]

env:
  ACTIONS_RUNNER_DEBUG: true
jobs:
  fast_and_unreliable_developer_deployment_test:
    if: github.repository == 'koo5/accounts-assessor'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: docker_scripts/first_run.sh
      - run: docker_scripts/up.sh
      - run: docker_scripts/down.sh & disown


